# Site settings
title: Tech Blog
email: your-email@example.com
description: >-
  Personal blog about software development, tech and projects.
  Notes, tutorials and brainstorming about the software development world.
baseurl: "/jekyll"
url: "https://chrisob194.github.io"
github_username: chrisob194
repository: chrisob194/jekyll

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Permalink format
permalink: /:year/:month/:day/:title/
